---
- name: Using notify and handlers
  hosts: all
  become: yes
  tasks: 
    - name: Install apache webserver in RedHat family     
      yum:
        name: httpd
        state: present
        update_cache: yes      
      when: ansible_facts['os_family']=="RedHat"
      tags: install

    - copy: 
        src: index.html
        dest: /var/www/html
      tags: copying
      notify: start apache webserver
    handlers:
    - name: start apache webserver   
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family']=="RedHat"   

    